"""add relevance tables

Revision ID: 15c2347f523e
Revises: d4113c00590c
Create Date: 2026-09-29 15:56:28.175586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '15c2347f523e'
down_revision: Union[str, Sequence[str], None] = 'd4113c00590c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_relevance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_no', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('brief', sa.Text(), nullable=True),
    sa.Column('ai_answer', sa.Text(), nullable=True),
    sa.Column('ai_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_relevance_reference_no'), 'ai_relevance', ['reference_no'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_no', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_reference_no'), 'feedback', ['reference_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_reference_no'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_ai_relevance_reference_no'), table_name='ai_relevance')
    op.drop_table('ai_relevance')
    # ### end Alembic commands ###
